[tools]
deno = "1.46"
yamllint = "latest"
yamlfmt = "latest"

[tasks."check:format"]
run = """
set -ex

deno fmt --check
deno run -A --no-lock npm:prettier -c "./**/*.{html,css}"
yamlfmt -dry -lint $(find . -name '*.yaml')
"""

[tasks."check:lint"]
run = """
set -ex

deno lint
deno run -A --no-lock npm:markdownlint-cli2 "**/*.{md,markdown}"
deno run -A --no-lock npm:html-validate $(find . -name '*.html')
yamllint $(find . -name '*.yaml')
"""
